#!/usr/bin/env python
"""
Simple script to convert WW BOTA to GeoJson
"""
import csv
import json
import sys

if __name__ == "__main__":

    features = []
    geojson = {
        "type": "FeatureCollection",
        "features": features
    }
    with open(sys.argv[1], newline='', encoding='utf-8-sig', errors='replace') as input_file:
        reader = csv.DictReader(input_file)

        for n, row in enumerate(reader, 2):
            if not row["Reference"]:  # Skip blank rows
                continue
            try:
                point = float(row['Long']), float(row['Lat'])
            except (ValueError, TypeError) as e:
                print(f"Error on line {n}: {e!r}", file=sys.stderr)
                continue
            features.append({
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": point,
                },
                "properties": {
                    "scheme": row["Scheme"].strip(),
                    "reference": row["Reference"],
                    "name": row["Name"],
                    "type": row["Type"],
                }
            })
    json.dump(geojson, sys.stdout, separators=(',', ':'))
